/**
 * This file is defined action constants
 */
export const CLEAR_PRODUCT_LIST = 'PRODUCTS:CLEAR_PRODUCT_LIST'
export const SET_IS_PRODUCT_LOADED = 'PRODUCTS:SET_IS_PRODUCT_LOADED'
export const FETCH_PRODUCT_LIST = 'PRODUCTS:FETCH_PRODUCT_LIST'
